version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306
